---
title: "Aula 8 - Conceitos de testes de hipótese"
author: "Rafael Bassi Stern"
date: 2018-04-18
output: html_document
---

# Testes de hipótese

É comum que queiramos saber o quanto
uma amostra corrobora uma hipótese científica.
Neste caso, podemos aplicar um teste de hipótese,
isto é, um procedimento que decidirá se
a hipótese é ou não rejeitada diante da amostra obtida.

Por exemplo, considere que $X_{1}, \ldots, X_{n}$ são
observações independentes realizadas com uma régua ao
medir um determinado objeto. Suponha que 
$X_{i} \sim N(\mu, \sigma_0^2)$, onde $\sigma_0^2$ é
conhecido e indica precisão das medidas feitas com a régua.
Uma pessoa poderia estar interessada na hipótese 
de que o objeto tem $15$ cm. Formalmente, 
chamamos esta hipótese de **hipótese nula** e
a representamos por $H_0: \mu = 15$.
Gostaríamos de saber se é possível 
rejeitar $H_0$ com base nos dados.

## Tipos de erro

Existem $4$ possíveis resultados que
podem decorrer de um teste de hipótese.
Note que o teste de hipótese pode rejeitar ou
não rejeitar a hipótese nula e, também,
esta hipótese pode ser verdadeira ou falsa.
Assim, existem $4$ combinações de resultados possíveis:

- (Acerto) A hipótese nula é verdadeira e não é rejeitada.
- (Acerto) A hipótese nula é falsa e é rejeitada.
- (Erro tipo I) A hipótese nula é verdadeira e é rejeitada.
- (Erro tipo II) A hipótese nula é falsa e não é rejeitada.

Estas combinações podem ser representadas na seguinte tabela:

```{r echo = FALSE, message = FALSE, warning = FALSE}
erros = data.frame(V1 = c("Rejeita H", "Não rejeita H"),
                   V2 = c("Erro tipo I", "Acerto"),
                   V3 = c("Acerto", "Erro tipo II"))
names(erros) = c("", "H é verdadeira", "H é falsa")
DT::datatable(erros, rownames = FALSE, options = list(dom = 't'))
```

Note que existe um balanço entre 
os erros tipo I e II.
Por exemplo, se quiséssemos 
que a probabilidade de cometer 
um erro tipo I fosse 0, 
então poderíamos nunca rejeitar H.
Contudo, neste caso, 
a probabilidade de cometer 
um erro tipo II seria 1.
Analogamente, se sempre rejeitarmos H,
então as probabilidades de erro tipo I e II
serão, respectivamente, 1 e 0.
Na prática, rejeitamos $H_0$ quando 
os dados oferecem evidência contrária a este hipótese.
Assim, buscamos que as probabilidades de cometer
um erro tipo I ou um erro tipo II sejam baixas.

Uma outra observação importante é que,
em geral, não sabemos se cometemos um erro em um teste de hipótese.
Para saber se $H_0$ é verdadeiro ou não,
seria necessária observar a população.
Como apenas somos capazes de observar a amostra,
não somos capazes de determinar se $H_0$ é verdadeiro ou não.
Assim, não sabemos se o resultado do teste de hipótese
foi um acerto ou um erro.

Apesar da limitação acima, podemos controlar 
as probabilidades de erro tipo I e II de um teste.
Isto é, podemos desenvolver testes que,
antes de observar o banco de dados, tenham
uma baixa probabilidade de cometer um erro.

Convecionou-se que a hipótese nula deve
ser escolhida de tal forma que 
o erro tipo I seja mais grave que o erro tipo II.
Por exemplo, é mais grave concluir que 
um rio não está poluído quando ele está poluído
do que concluir que ele está poluído quando de fato não está.
Assim, neste caso, tomaríamos a hipótese nula como
aquela de que o rio está poluído, pois assim o
erro tipo I seria o de rejeitar que o rio está poluído 
quando ele de fato está.

Como o erro tipo I é o mais grave,
construímos testes de hipótese que diretamente
controlam a probabilidade de erro tipo I.
Formalmente, determinaremos testes de hipótese tais que
o erro tipo I seja menor que um valor pré-determinado, $\alpha$.
É comum que $\alpha$ seja chamado de 
**nível de significância** do teste.

## Exemplo: normal com variância conhecida

Considere que $X_{1},\ldots,X_{n}$ são 
observações independentes e tais que 
$X_{i} \sim N(\mu,\sigma_0^2)$, onde 
$\sigma_0^2$ é conhecido. Por exemplo,
$X_i$ pode ser o peso da $i$-ésima vaca
alimentada com uma determinada ração.
Deseja-se provar que o peso médio de
vacas alimentadas com esta ração seja maior que
$500 kg$, ou seja, a hipótese nula é
$H_0: \mu \leq 500$.


